if(EXISTS "/home/lbh/leanstore-vmcache-main/test/TestGroupCommit[1]_tests.cmake")
  include("/home/lbh/leanstore-vmcache-main/test/TestGroupCommit[1]_tests.cmake")
else()
  add_test(TestGroupCommit_NOT_BUILT TestGroupCommit_NOT_BUILT)
endif()
