if(EXISTS "/home/lbh/leanstore-vmcache-main/test/TestLeanStoreAdapter[1]_tests.cmake")
  include("/home/lbh/leanstore-vmcache-main/test/TestLeanStoreAdapter[1]_tests.cmake")
else()
  add_test(TestLeanStoreAdapter_NOT_BUILT TestLeanStoreAdapter_NOT_BUILT)
endif()
