if(EXISTS "/home/lbh/leanstore-vmcache-main/test/TestBTree[1]_tests.cmake")
  include("/home/lbh/leanstore-vmcache-main/test/TestBTree[1]_tests.cmake")
else()
  add_test(TestBTree_NOT_BUILT TestBTree_NOT_BUILT)
endif()
