if(EXISTS "/home/lbh/leanstore-vmcache-main/test/TestAioInterface[1]_tests.cmake")
  include("/home/lbh/leanstore-vmcache-main/test/TestAioInterface[1]_tests.cmake")
else()
  add_test(TestAioInterface_NOT_BUILT TestAioInterface_NOT_BUILT)
endif()
