if(EXISTS "/home/lbh/leanstore-vmcache-main/test/TestFilesystemAdapter[1]_tests.cmake")
  include("/home/lbh/leanstore-vmcache-main/test/TestFilesystemAdapter[1]_tests.cmake")
else()
  add_test(TestFilesystemAdapter_NOT_BUILT TestFilesystemAdapter_NOT_BUILT)
endif()
