# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lbh/git/LeanStoreOOPW

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lbh/git/LeanStoreOOPW

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/lbh/git/LeanStoreOOPW/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lbh/git/LeanStoreOOPW/CMakeFiles /home/lbh/git/LeanStoreOOPW//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lbh/git/LeanStoreOOPW/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named format

# Build rule for target.
format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 format
.PHONY : format

# fast build rule for target.
format/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/format.dir/build.make CMakeFiles/format.dir/build
.PHONY : format/fast

#=============================================================================
# Target rules for targets named check-format

# Build rule for target.
check-format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check-format
.PHONY : check-format

# fast build rule for target.
check-format/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check-format.dir/build.make CMakeFiles/check-format.dir/build
.PHONY : check-format/fast

#=============================================================================
# Target rules for targets named check-tidy

# Build rule for target.
check-tidy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check-tidy
.PHONY : check-tidy

# fast build rule for target.
check-tidy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check-tidy.dir/build.make CMakeFiles/check-tidy.dir/build
.PHONY : check-tidy/fast

#=============================================================================
# Target rules for targets named check-tidy-full

# Build rule for target.
check-tidy-full: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check-tidy-full
.PHONY : check-tidy-full

# fast build rule for target.
check-tidy-full/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check-tidy-full.dir/build.make CMakeFiles/check-tidy-full.dir/build
.PHONY : check-tidy-full/fast

#=============================================================================
# Target rules for targets named leanstore

# Build rule for target.
leanstore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 leanstore
.PHONY : leanstore

# fast build rule for target.
leanstore/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/build
.PHONY : leanstore/fast

#=============================================================================
# Target rules for targets named croaring

# Build rule for target.
croaring: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 croaring
.PHONY : croaring

# fast build rule for target.
croaring/fast:
	$(MAKE) $(MAKESILENT) -f share_libs/croaring/CMakeFiles/croaring.dir/build.make share_libs/croaring/CMakeFiles/croaring.dir/build
.PHONY : croaring/fast

#=============================================================================
# Target rules for targets named fsst

# Build rule for target.
fsst: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fsst
.PHONY : fsst

# fast build rule for target.
fsst/fast:
	$(MAKE) $(MAKESILENT) -f share_libs/fsst/CMakeFiles/fsst.dir/build.make share_libs/fsst/CMakeFiles/fsst.dir/build
.PHONY : fsst/fast

#=============================================================================
# Target rules for targets named pqxx

# Build rule for target.
pqxx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pqxx
.PHONY : pqxx

# fast build rule for target.
pqxx/fast:
	$(MAKE) $(MAKESILENT) -f share_libs/libpqxx/src/CMakeFiles/pqxx.dir/build.make share_libs/libpqxx/src/CMakeFiles/pqxx.dir/build
.PHONY : pqxx/fast

#=============================================================================
# Target rules for targets named LibLz4

# Build rule for target.
LibLz4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LibLz4
.PHONY : LibLz4

# fast build rule for target.
LibLz4/fast:
	$(MAKE) $(MAKESILENT) -f share_libs/lz4/CMakeFiles/LibLz4.dir/build.make share_libs/lz4/CMakeFiles/LibLz4.dir/build
.PHONY : LibLz4/fast

#=============================================================================
# Target rules for targets named sha256

# Build rule for target.
sha256: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sha256
.PHONY : sha256

# fast build rule for target.
sha256/fast:
	$(MAKE) $(MAKESILENT) -f share_libs/sha256/CMakeFiles/sha256.dir/build.make share_libs/sha256/CMakeFiles/sha256.dir/build
.PHONY : sha256/fast

#=============================================================================
# Target rules for targets named typefold

# Build rule for target.
typefold: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 typefold
.PHONY : typefold

# fast build rule for target.
typefold/fast:
	$(MAKE) $(MAKESILENT) -f share_libs/typefold/CMakeFiles/typefold.dir/build.make share_libs/typefold/CMakeFiles/typefold.dir/build
.PHONY : typefold/fast

#=============================================================================
# Target rules for targets named Libyyjson

# Build rule for target.
Libyyjson: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Libyyjson
.PHONY : Libyyjson

# fast build rule for target.
Libyyjson/fast:
	$(MAKE) $(MAKESILENT) -f share_libs/yyjson/CMakeFiles/Libyyjson.dir/build.make share_libs/yyjson/CMakeFiles/Libyyjson.dir/build
.PHONY : Libyyjson/fast

#=============================================================================
# Target rules for targets named leanstore_bm

# Build rule for target.
leanstore_bm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 leanstore_bm
.PHONY : leanstore_bm

# fast build rule for target.
leanstore_bm/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/leanstore_bm.dir/build.make benchmark/CMakeFiles/leanstore_bm.dir/build
.PHONY : leanstore_bm/fast

#=============================================================================
# Target rules for targets named LeanStore_TPCC

# Build rule for target.
LeanStore_TPCC: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LeanStore_TPCC
.PHONY : LeanStore_TPCC

# fast build rule for target.
LeanStore_TPCC/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/LeanStore_TPCC.dir/build.make benchmark/CMakeFiles/LeanStore_TPCC.dir/build
.PHONY : LeanStore_TPCC/fast

#=============================================================================
# Target rules for targets named LeanStore_YCSB

# Build rule for target.
LeanStore_YCSB: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LeanStore_YCSB
.PHONY : LeanStore_YCSB

# fast build rule for target.
LeanStore_YCSB/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/LeanStore_YCSB.dir/build.make benchmark/CMakeFiles/LeanStore_YCSB.dir/build
.PHONY : LeanStore_YCSB/fast

#=============================================================================
# Target rules for targets named LeanStore_FB_WebServer

# Build rule for target.
LeanStore_FB_WebServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LeanStore_FB_WebServer
.PHONY : LeanStore_FB_WebServer

# fast build rule for target.
LeanStore_FB_WebServer/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/LeanStore_FB_WebServer.dir/build.make benchmark/CMakeFiles/LeanStore_FB_WebServer.dir/build
.PHONY : LeanStore_FB_WebServer/fast

#=============================================================================
# Target rules for targets named LeanStore_Wiki

# Build rule for target.
LeanStore_Wiki: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LeanStore_Wiki
.PHONY : LeanStore_Wiki

# fast build rule for target.
LeanStore_Wiki/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/LeanStore_Wiki.dir/build.make benchmark/CMakeFiles/LeanStore_Wiki.dir/build
.PHONY : LeanStore_Wiki/fast

#=============================================================================
# Target rules for targets named LeanStore_Gitclone

# Build rule for target.
LeanStore_Gitclone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LeanStore_Gitclone
.PHONY : LeanStore_Gitclone

# fast build rule for target.
LeanStore_Gitclone/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/LeanStore_Gitclone.dir/build.make benchmark/CMakeFiles/LeanStore_Gitclone.dir/build
.PHONY : LeanStore_Gitclone/fast

#=============================================================================
# Target rules for targets named LeanStore_IndexWiki

# Build rule for target.
LeanStore_IndexWiki: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LeanStore_IndexWiki
.PHONY : LeanStore_IndexWiki

# fast build rule for target.
LeanStore_IndexWiki/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/LeanStore_IndexWiki.dir/build.make benchmark/CMakeFiles/LeanStore_IndexWiki.dir/build
.PHONY : LeanStore_IndexWiki/fast

#=============================================================================
# Target rules for targets named LeanStore_Aging

# Build rule for target.
LeanStore_Aging: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LeanStore_Aging
.PHONY : LeanStore_Aging

# fast build rule for target.
LeanStore_Aging/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/LeanStore_Aging.dir/build.make benchmark/CMakeFiles/LeanStore_Aging.dir/build
.PHONY : LeanStore_Aging/fast

#=============================================================================
# Target rules for targets named Filesystem_YCSB

# Build rule for target.
Filesystem_YCSB: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Filesystem_YCSB
.PHONY : Filesystem_YCSB

# fast build rule for target.
Filesystem_YCSB/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/Filesystem_YCSB.dir/build.make benchmark/CMakeFiles/Filesystem_YCSB.dir/build
.PHONY : Filesystem_YCSB/fast

#=============================================================================
# Target rules for targets named Filesystem_Wiki

# Build rule for target.
Filesystem_Wiki: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Filesystem_Wiki
.PHONY : Filesystem_Wiki

# fast build rule for target.
Filesystem_Wiki/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/Filesystem_Wiki.dir/build.make benchmark/CMakeFiles/Filesystem_Wiki.dir/build
.PHONY : Filesystem_Wiki/fast

#=============================================================================
# Target rules for targets named Filesystem_Gitclone

# Build rule for target.
Filesystem_Gitclone: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Filesystem_Gitclone
.PHONY : Filesystem_Gitclone

# fast build rule for target.
Filesystem_Gitclone/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/Filesystem_Gitclone.dir/build.make benchmark/CMakeFiles/Filesystem_Gitclone.dir/build
.PHONY : Filesystem_Gitclone/fast

#=============================================================================
# Target rules for targets named Filesystem_Aging

# Build rule for target.
Filesystem_Aging: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Filesystem_Aging
.PHONY : Filesystem_Aging

# fast build rule for target.
Filesystem_Aging/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/Filesystem_Aging.dir/build.make benchmark/CMakeFiles/Filesystem_Aging.dir/build
.PHONY : Filesystem_Aging/fast

#=============================================================================
# Target rules for targets named SQLite_YCSB

# Build rule for target.
SQLite_YCSB: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SQLite_YCSB
.PHONY : SQLite_YCSB

# fast build rule for target.
SQLite_YCSB/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/SQLite_YCSB.dir/build.make benchmark/CMakeFiles/SQLite_YCSB.dir/build
.PHONY : SQLite_YCSB/fast

#=============================================================================
# Target rules for targets named Postgres_YCSB

# Build rule for target.
Postgres_YCSB: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Postgres_YCSB
.PHONY : Postgres_YCSB

# fast build rule for target.
Postgres_YCSB/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/Postgres_YCSB.dir/build.make benchmark/CMakeFiles/Postgres_YCSB.dir/build
.PHONY : Postgres_YCSB/fast

#=============================================================================
# Target rules for targets named MySQL_YCSB

# Build rule for target.
MySQL_YCSB: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MySQL_YCSB
.PHONY : MySQL_YCSB

# fast build rule for target.
MySQL_YCSB/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/MySQL_YCSB.dir/build.make benchmark/CMakeFiles/MySQL_YCSB.dir/build
.PHONY : MySQL_YCSB/fast

#=============================================================================
# Target rules for targets named MicroSHA2

# Build rule for target.
MicroSHA2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MicroSHA2
.PHONY : MicroSHA2

# fast build rule for target.
MicroSHA2/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/MicroSHA2.dir/build.make benchmark/CMakeFiles/MicroSHA2.dir/build
.PHONY : MicroSHA2/fast

#=============================================================================
# Target rules for targets named MicroCompression

# Build rule for target.
MicroCompression: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MicroCompression
.PHONY : MicroCompression

# fast build rule for target.
MicroCompression/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/MicroCompression.dir/build.make benchmark/CMakeFiles/MicroCompression.dir/build
.PHONY : MicroCompression/fast

#=============================================================================
# Target rules for targets named MicroFreePages

# Build rule for target.
MicroFreePages: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MicroFreePages
.PHONY : MicroFreePages

# fast build rule for target.
MicroFreePages/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/MicroFreePages.dir/build.make benchmark/CMakeFiles/MicroFreePages.dir/build
.PHONY : MicroFreePages/fast

#=============================================================================
# Target rules for targets named MicroQueue

# Build rule for target.
MicroQueue: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MicroQueue
.PHONY : MicroQueue

# fast build rule for target.
MicroQueue/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/MicroQueue.dir/build.make benchmark/CMakeFiles/MicroQueue.dir/build
.PHONY : MicroQueue/fast

#=============================================================================
# Target rules for targets named MicroBitmap

# Build rule for target.
MicroBitmap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MicroBitmap
.PHONY : MicroBitmap

# fast build rule for target.
MicroBitmap/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/MicroBitmap.dir/build.make benchmark/CMakeFiles/MicroBitmap.dir/build
.PHONY : MicroBitmap/fast

#=============================================================================
# Target rules for targets named MicroSearch

# Build rule for target.
MicroSearch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MicroSearch
.PHONY : MicroSearch

# fast build rule for target.
MicroSearch/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/MicroSearch.dir/build.make benchmark/CMakeFiles/MicroSearch.dir/build
.PHONY : MicroSearch/fast

#=============================================================================
# Target rules for targets named LeanStore_Email

# Build rule for target.
LeanStore_Email: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LeanStore_Email
.PHONY : LeanStore_Email

# fast build rule for target.
LeanStore_Email/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/LeanStore_Email.dir/build.make benchmark/CMakeFiles/LeanStore_Email.dir/build
.PHONY : LeanStore_Email/fast

#=============================================================================
# Target rules for targets named LeanStore_URL

# Build rule for target.
LeanStore_URL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LeanStore_URL
.PHONY : LeanStore_URL

# fast build rule for target.
LeanStore_URL/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/LeanStore_URL.dir/build.make benchmark/CMakeFiles/LeanStore_URL.dir/build
.PHONY : LeanStore_URL/fast

#=============================================================================
# Target rules for targets named LeanStore_WikiTitle

# Build rule for target.
LeanStore_WikiTitle: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LeanStore_WikiTitle
.PHONY : LeanStore_WikiTitle

# fast build rule for target.
LeanStore_WikiTitle/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/LeanStore_WikiTitle.dir/build.make benchmark/CMakeFiles/LeanStore_WikiTitle.dir/build
.PHONY : LeanStore_WikiTitle/fast

#=============================================================================
# Target rules for targets named LeanStore_Flashbench

# Build rule for target.
LeanStore_Flashbench: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LeanStore_Flashbench
.PHONY : LeanStore_Flashbench

# fast build rule for target.
LeanStore_Flashbench/fast:
	$(MAKE) $(MAKESILENT) -f benchmark/CMakeFiles/LeanStore_Flashbench.dir/build.make benchmark/CMakeFiles/LeanStore_Flashbench.dir/build
.PHONY : LeanStore_Flashbench/fast

src/buffer/buffer_manager.o: src/buffer/buffer_manager.cc.o
.PHONY : src/buffer/buffer_manager.o

# target to build an object file
src/buffer/buffer_manager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/buffer/buffer_manager.cc.o
.PHONY : src/buffer/buffer_manager.cc.o

src/buffer/buffer_manager.i: src/buffer/buffer_manager.cc.i
.PHONY : src/buffer/buffer_manager.i

# target to preprocess a source file
src/buffer/buffer_manager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/buffer/buffer_manager.cc.i
.PHONY : src/buffer/buffer_manager.cc.i

src/buffer/buffer_manager.s: src/buffer/buffer_manager.cc.s
.PHONY : src/buffer/buffer_manager.s

# target to generate assembly for a file
src/buffer/buffer_manager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/buffer/buffer_manager.cc.s
.PHONY : src/buffer/buffer_manager.cc.s

src/buffer/resident_set.o: src/buffer/resident_set.cc.o
.PHONY : src/buffer/resident_set.o

# target to build an object file
src/buffer/resident_set.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/buffer/resident_set.cc.o
.PHONY : src/buffer/resident_set.cc.o

src/buffer/resident_set.i: src/buffer/resident_set.cc.i
.PHONY : src/buffer/resident_set.i

# target to preprocess a source file
src/buffer/resident_set.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/buffer/resident_set.cc.i
.PHONY : src/buffer/resident_set.cc.i

src/buffer/resident_set.s: src/buffer/resident_set.cc.s
.PHONY : src/buffer/resident_set.s

# target to generate assembly for a file
src/buffer/resident_set.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/buffer/resident_set.cc.s
.PHONY : src/buffer/resident_set.cc.s

src/common/concurrent_queue.o: src/common/concurrent_queue.cc.o
.PHONY : src/common/concurrent_queue.o

# target to build an object file
src/common/concurrent_queue.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/common/concurrent_queue.cc.o
.PHONY : src/common/concurrent_queue.cc.o

src/common/concurrent_queue.i: src/common/concurrent_queue.cc.i
.PHONY : src/common/concurrent_queue.i

# target to preprocess a source file
src/common/concurrent_queue.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/common/concurrent_queue.cc.i
.PHONY : src/common/concurrent_queue.cc.i

src/common/concurrent_queue.s: src/common/concurrent_queue.cc.s
.PHONY : src/common/concurrent_queue.s

# target to generate assembly for a file
src/common/concurrent_queue.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/common/concurrent_queue.cc.s
.PHONY : src/common/concurrent_queue.cc.s

src/common/utils.o: src/common/utils.cc.o
.PHONY : src/common/utils.o

# target to build an object file
src/common/utils.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/common/utils.cc.o
.PHONY : src/common/utils.cc.o

src/common/utils.i: src/common/utils.cc.i
.PHONY : src/common/utils.i

# target to preprocess a source file
src/common/utils.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/common/utils.cc.i
.PHONY : src/common/utils.cc.i

src/common/utils.s: src/common/utils.cc.s
.PHONY : src/common/utils.s

# target to generate assembly for a file
src/common/utils.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/common/utils.cc.s
.PHONY : src/common/utils.cc.s

src/common/worker_pool.o: src/common/worker_pool.cc.o
.PHONY : src/common/worker_pool.o

# target to build an object file
src/common/worker_pool.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/common/worker_pool.cc.o
.PHONY : src/common/worker_pool.cc.o

src/common/worker_pool.i: src/common/worker_pool.cc.i
.PHONY : src/common/worker_pool.i

# target to preprocess a source file
src/common/worker_pool.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/common/worker_pool.cc.i
.PHONY : src/common/worker_pool.cc.i

src/common/worker_pool.s: src/common/worker_pool.cc.s
.PHONY : src/common/worker_pool.s

# target to generate assembly for a file
src/common/worker_pool.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/common/worker_pool.cc.s
.PHONY : src/common/worker_pool.cc.s

src/config.o: src/config.cc.o
.PHONY : src/config.o

# target to build an object file
src/config.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/config.cc.o
.PHONY : src/config.cc.o

src/config.i: src/config.cc.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/config.cc.i
.PHONY : src/config.cc.i

src/config.s: src/config.cc.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/config.cc.s
.PHONY : src/config.cc.s

src/env.o: src/env.cc.o
.PHONY : src/env.o

# target to build an object file
src/env.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/env.cc.o
.PHONY : src/env.cc.o

src/env.i: src/env.cc.i
.PHONY : src/env.i

# target to preprocess a source file
src/env.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/env.cc.i
.PHONY : src/env.cc.i

src/env.s: src/env.cc.s
.PHONY : src/env.s

# target to generate assembly for a file
src/env.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/env.cc.s
.PHONY : src/env.cc.s

src/leanstore.o: src/leanstore.cc.o
.PHONY : src/leanstore.o

# target to build an object file
src/leanstore.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/leanstore.cc.o
.PHONY : src/leanstore.cc.o

src/leanstore.i: src/leanstore.cc.i
.PHONY : src/leanstore.i

# target to preprocess a source file
src/leanstore.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/leanstore.cc.i
.PHONY : src/leanstore.cc.i

src/leanstore.s: src/leanstore.cc.s
.PHONY : src/leanstore.s

# target to generate assembly for a file
src/leanstore.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/leanstore.cc.s
.PHONY : src/leanstore.cc.s

src/recovery/group_commit.o: src/recovery/group_commit.cc.o
.PHONY : src/recovery/group_commit.o

# target to build an object file
src/recovery/group_commit.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/recovery/group_commit.cc.o
.PHONY : src/recovery/group_commit.cc.o

src/recovery/group_commit.i: src/recovery/group_commit.cc.i
.PHONY : src/recovery/group_commit.i

# target to preprocess a source file
src/recovery/group_commit.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/recovery/group_commit.cc.i
.PHONY : src/recovery/group_commit.cc.i

src/recovery/group_commit.s: src/recovery/group_commit.cc.s
.PHONY : src/recovery/group_commit.s

# target to generate assembly for a file
src/recovery/group_commit.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/recovery/group_commit.cc.s
.PHONY : src/recovery/group_commit.cc.s

src/recovery/log_manager.o: src/recovery/log_manager.cc.o
.PHONY : src/recovery/log_manager.o

# target to build an object file
src/recovery/log_manager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/recovery/log_manager.cc.o
.PHONY : src/recovery/log_manager.cc.o

src/recovery/log_manager.i: src/recovery/log_manager.cc.i
.PHONY : src/recovery/log_manager.i

# target to preprocess a source file
src/recovery/log_manager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/recovery/log_manager.cc.i
.PHONY : src/recovery/log_manager.cc.i

src/recovery/log_manager.s: src/recovery/log_manager.cc.s
.PHONY : src/recovery/log_manager.s

# target to generate assembly for a file
src/recovery/log_manager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/recovery/log_manager.cc.s
.PHONY : src/recovery/log_manager.cc.s

src/recovery/log_worker.o: src/recovery/log_worker.cc.o
.PHONY : src/recovery/log_worker.o

# target to build an object file
src/recovery/log_worker.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/recovery/log_worker.cc.o
.PHONY : src/recovery/log_worker.cc.o

src/recovery/log_worker.i: src/recovery/log_worker.cc.i
.PHONY : src/recovery/log_worker.i

# target to preprocess a source file
src/recovery/log_worker.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/recovery/log_worker.cc.i
.PHONY : src/recovery/log_worker.cc.i

src/recovery/log_worker.s: src/recovery/log_worker.cc.s
.PHONY : src/recovery/log_worker.s

# target to generate assembly for a file
src/recovery/log_worker.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/recovery/log_worker.cc.s
.PHONY : src/recovery/log_worker.cc.s

src/statistics.o: src/statistics.cc.o
.PHONY : src/statistics.o

# target to build an object file
src/statistics.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/statistics.cc.o
.PHONY : src/statistics.cc.o

src/statistics.i: src/statistics.cc.i
.PHONY : src/statistics.i

# target to preprocess a source file
src/statistics.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/statistics.cc.i
.PHONY : src/statistics.cc.i

src/statistics.s: src/statistics.cc.s
.PHONY : src/statistics.s

# target to generate assembly for a file
src/statistics.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/statistics.cc.s
.PHONY : src/statistics.cc.s

src/storage/blob/blob_manager.o: src/storage/blob/blob_manager.cc.o
.PHONY : src/storage/blob/blob_manager.o

# target to build an object file
src/storage/blob/blob_manager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/blob/blob_manager.cc.o
.PHONY : src/storage/blob/blob_manager.cc.o

src/storage/blob/blob_manager.i: src/storage/blob/blob_manager.cc.i
.PHONY : src/storage/blob/blob_manager.i

# target to preprocess a source file
src/storage/blob/blob_manager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/blob/blob_manager.cc.i
.PHONY : src/storage/blob/blob_manager.cc.i

src/storage/blob/blob_manager.s: src/storage/blob/blob_manager.cc.s
.PHONY : src/storage/blob/blob_manager.s

# target to generate assembly for a file
src/storage/blob/blob_manager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/blob/blob_manager.cc.s
.PHONY : src/storage/blob/blob_manager.cc.s

src/storage/blob/compressor.o: src/storage/blob/compressor.cc.o
.PHONY : src/storage/blob/compressor.o

# target to build an object file
src/storage/blob/compressor.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/blob/compressor.cc.o
.PHONY : src/storage/blob/compressor.cc.o

src/storage/blob/compressor.i: src/storage/blob/compressor.cc.i
.PHONY : src/storage/blob/compressor.i

# target to preprocess a source file
src/storage/blob/compressor.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/blob/compressor.cc.i
.PHONY : src/storage/blob/compressor.cc.i

src/storage/blob/compressor.s: src/storage/blob/compressor.cc.s
.PHONY : src/storage/blob/compressor.s

# target to generate assembly for a file
src/storage/blob/compressor.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/blob/compressor.cc.s
.PHONY : src/storage/blob/compressor.cc.s

src/storage/btree/locking.o: src/storage/btree/locking.cc.o
.PHONY : src/storage/btree/locking.o

# target to build an object file
src/storage/btree/locking.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/btree/locking.cc.o
.PHONY : src/storage/btree/locking.cc.o

src/storage/btree/locking.i: src/storage/btree/locking.cc.i
.PHONY : src/storage/btree/locking.i

# target to preprocess a source file
src/storage/btree/locking.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/btree/locking.cc.i
.PHONY : src/storage/btree/locking.cc.i

src/storage/btree/locking.s: src/storage/btree/locking.cc.s
.PHONY : src/storage/btree/locking.s

# target to generate assembly for a file
src/storage/btree/locking.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/btree/locking.cc.s
.PHONY : src/storage/btree/locking.cc.s

src/storage/btree/node.o: src/storage/btree/node.cc.o
.PHONY : src/storage/btree/node.o

# target to build an object file
src/storage/btree/node.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/btree/node.cc.o
.PHONY : src/storage/btree/node.cc.o

src/storage/btree/node.i: src/storage/btree/node.cc.i
.PHONY : src/storage/btree/node.i

# target to preprocess a source file
src/storage/btree/node.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/btree/node.cc.i
.PHONY : src/storage/btree/node.cc.i

src/storage/btree/node.s: src/storage/btree/node.cc.s
.PHONY : src/storage/btree/node.s

# target to generate assembly for a file
src/storage/btree/node.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/btree/node.cc.s
.PHONY : src/storage/btree/node.cc.s

src/storage/btree/tree.o: src/storage/btree/tree.cc.o
.PHONY : src/storage/btree/tree.o

# target to build an object file
src/storage/btree/tree.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/btree/tree.cc.o
.PHONY : src/storage/btree/tree.cc.o

src/storage/btree/tree.i: src/storage/btree/tree.cc.i
.PHONY : src/storage/btree/tree.i

# target to preprocess a source file
src/storage/btree/tree.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/btree/tree.cc.i
.PHONY : src/storage/btree/tree.cc.i

src/storage/btree/tree.s: src/storage/btree/tree.cc.s
.PHONY : src/storage/btree/tree.s

# target to generate assembly for a file
src/storage/btree/tree.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/btree/tree.cc.s
.PHONY : src/storage/btree/tree.cc.s

src/storage/extent/extent_list.o: src/storage/extent/extent_list.cc.o
.PHONY : src/storage/extent/extent_list.o

# target to build an object file
src/storage/extent/extent_list.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/extent/extent_list.cc.o
.PHONY : src/storage/extent/extent_list.cc.o

src/storage/extent/extent_list.i: src/storage/extent/extent_list.cc.i
.PHONY : src/storage/extent/extent_list.i

# target to preprocess a source file
src/storage/extent/extent_list.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/extent/extent_list.cc.i
.PHONY : src/storage/extent/extent_list.cc.i

src/storage/extent/extent_list.s: src/storage/extent/extent_list.cc.s
.PHONY : src/storage/extent/extent_list.s

# target to generate assembly for a file
src/storage/extent/extent_list.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/extent/extent_list.cc.s
.PHONY : src/storage/extent/extent_list.cc.s

src/storage/free_page_manager.o: src/storage/free_page_manager.cc.o
.PHONY : src/storage/free_page_manager.o

# target to build an object file
src/storage/free_page_manager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/free_page_manager.cc.o
.PHONY : src/storage/free_page_manager.cc.o

src/storage/free_page_manager.i: src/storage/free_page_manager.cc.i
.PHONY : src/storage/free_page_manager.i

# target to preprocess a source file
src/storage/free_page_manager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/free_page_manager.cc.i
.PHONY : src/storage/free_page_manager.cc.i

src/storage/free_page_manager.s: src/storage/free_page_manager.cc.s
.PHONY : src/storage/free_page_manager.s

# target to generate assembly for a file
src/storage/free_page_manager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/free_page_manager.cc.s
.PHONY : src/storage/free_page_manager.cc.s

src/storage/space/backend/aio.o: src/storage/space/backend/aio.cc.o
.PHONY : src/storage/space/backend/aio.o

# target to build an object file
src/storage/space/backend/aio.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/backend/aio.cc.o
.PHONY : src/storage/space/backend/aio.cc.o

src/storage/space/backend/aio.i: src/storage/space/backend/aio.cc.i
.PHONY : src/storage/space/backend/aio.i

# target to preprocess a source file
src/storage/space/backend/aio.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/backend/aio.cc.i
.PHONY : src/storage/space/backend/aio.cc.i

src/storage/space/backend/aio.s: src/storage/space/backend/aio.cc.s
.PHONY : src/storage/space/backend/aio.s

# target to generate assembly for a file
src/storage/space/backend/aio.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/backend/aio.cc.s
.PHONY : src/storage/space/backend/aio.cc.s

src/storage/space/backend/io_backend.o: src/storage/space/backend/io_backend.cc.o
.PHONY : src/storage/space/backend/io_backend.o

# target to build an object file
src/storage/space/backend/io_backend.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/backend/io_backend.cc.o
.PHONY : src/storage/space/backend/io_backend.cc.o

src/storage/space/backend/io_backend.i: src/storage/space/backend/io_backend.cc.i
.PHONY : src/storage/space/backend/io_backend.i

# target to preprocess a source file
src/storage/space/backend/io_backend.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/backend/io_backend.cc.i
.PHONY : src/storage/space/backend/io_backend.cc.i

src/storage/space/backend/io_backend.s: src/storage/space/backend/io_backend.cc.s
.PHONY : src/storage/space/backend/io_backend.s

# target to generate assembly for a file
src/storage/space/backend/io_backend.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/backend/io_backend.cc.s
.PHONY : src/storage/space/backend/io_backend.cc.s

src/storage/space/backend/zns.o: src/storage/space/backend/zns.cc.o
.PHONY : src/storage/space/backend/zns.o

# target to build an object file
src/storage/space/backend/zns.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/backend/zns.cc.o
.PHONY : src/storage/space/backend/zns.cc.o

src/storage/space/backend/zns.i: src/storage/space/backend/zns.cc.i
.PHONY : src/storage/space/backend/zns.i

# target to preprocess a source file
src/storage/space/backend/zns.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/backend/zns.cc.i
.PHONY : src/storage/space/backend/zns.cc.i

src/storage/space/backend/zns.s: src/storage/space/backend/zns.cc.s
.PHONY : src/storage/space/backend/zns.s

# target to generate assembly for a file
src/storage/space/backend/zns.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/backend/zns.cc.s
.PHONY : src/storage/space/backend/zns.cc.s

src/storage/space/device.o: src/storage/space/device.cc.o
.PHONY : src/storage/space/device.o

# target to build an object file
src/storage/space/device.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/device.cc.o
.PHONY : src/storage/space/device.cc.o

src/storage/space/device.i: src/storage/space/device.cc.i
.PHONY : src/storage/space/device.i

# target to preprocess a source file
src/storage/space/device.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/device.cc.i
.PHONY : src/storage/space/device.cc.i

src/storage/space/device.s: src/storage/space/device.cc.s
.PHONY : src/storage/space/device.s

# target to generate assembly for a file
src/storage/space/device.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/device.cc.s
.PHONY : src/storage/space/device.cc.s

src/storage/space/doublewrite.o: src/storage/space/doublewrite.cc.o
.PHONY : src/storage/space/doublewrite.o

# target to build an object file
src/storage/space/doublewrite.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/doublewrite.cc.o
.PHONY : src/storage/space/doublewrite.cc.o

src/storage/space/doublewrite.i: src/storage/space/doublewrite.cc.i
.PHONY : src/storage/space/doublewrite.i

# target to preprocess a source file
src/storage/space/doublewrite.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/doublewrite.cc.i
.PHONY : src/storage/space/doublewrite.cc.i

src/storage/space/doublewrite.s: src/storage/space/doublewrite.cc.s
.PHONY : src/storage/space/doublewrite.s

# target to generate assembly for a file
src/storage/space/doublewrite.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/doublewrite.cc.s
.PHONY : src/storage/space/doublewrite.cc.s

src/storage/space/garbage_collector.o: src/storage/space/garbage_collector.cc.o
.PHONY : src/storage/space/garbage_collector.o

# target to build an object file
src/storage/space/garbage_collector.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/garbage_collector.cc.o
.PHONY : src/storage/space/garbage_collector.cc.o

src/storage/space/garbage_collector.i: src/storage/space/garbage_collector.cc.i
.PHONY : src/storage/space/garbage_collector.i

# target to preprocess a source file
src/storage/space/garbage_collector.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/garbage_collector.cc.i
.PHONY : src/storage/space/garbage_collector.cc.i

src/storage/space/garbage_collector.s: src/storage/space/garbage_collector.cc.s
.PHONY : src/storage/space/garbage_collector.s

# target to generate assembly for a file
src/storage/space/garbage_collector.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/garbage_collector.cc.s
.PHONY : src/storage/space/garbage_collector.cc.s

src/storage/space/io_interface.o: src/storage/space/io_interface.cc.o
.PHONY : src/storage/space/io_interface.o

# target to build an object file
src/storage/space/io_interface.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/io_interface.cc.o
.PHONY : src/storage/space/io_interface.cc.o

src/storage/space/io_interface.i: src/storage/space/io_interface.cc.i
.PHONY : src/storage/space/io_interface.i

# target to preprocess a source file
src/storage/space/io_interface.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/io_interface.cc.i
.PHONY : src/storage/space/io_interface.cc.i

src/storage/space/io_interface.s: src/storage/space/io_interface.cc.s
.PHONY : src/storage/space/io_interface.s

# target to generate assembly for a file
src/storage/space/io_interface.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/io_interface.cc.s
.PHONY : src/storage/space/io_interface.cc.s

src/storage/space/space_manager.o: src/storage/space/space_manager.cc.o
.PHONY : src/storage/space/space_manager.o

# target to build an object file
src/storage/space/space_manager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/space_manager.cc.o
.PHONY : src/storage/space/space_manager.cc.o

src/storage/space/space_manager.i: src/storage/space/space_manager.cc.i
.PHONY : src/storage/space/space_manager.i

# target to preprocess a source file
src/storage/space/space_manager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/space_manager.cc.i
.PHONY : src/storage/space/space_manager.cc.i

src/storage/space/space_manager.s: src/storage/space/space_manager.cc.s
.PHONY : src/storage/space/space_manager.s

# target to generate assembly for a file
src/storage/space/space_manager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/storage/space/space_manager.cc.s
.PHONY : src/storage/space/space_manager.cc.s

src/sync/hybrid_guard.o: src/sync/hybrid_guard.cc.o
.PHONY : src/sync/hybrid_guard.o

# target to build an object file
src/sync/hybrid_guard.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/hybrid_guard.cc.o
.PHONY : src/sync/hybrid_guard.cc.o

src/sync/hybrid_guard.i: src/sync/hybrid_guard.cc.i
.PHONY : src/sync/hybrid_guard.i

# target to preprocess a source file
src/sync/hybrid_guard.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/hybrid_guard.cc.i
.PHONY : src/sync/hybrid_guard.cc.i

src/sync/hybrid_guard.s: src/sync/hybrid_guard.cc.s
.PHONY : src/sync/hybrid_guard.s

# target to generate assembly for a file
src/sync/hybrid_guard.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/hybrid_guard.cc.s
.PHONY : src/sync/hybrid_guard.cc.s

src/sync/hybrid_latch.o: src/sync/hybrid_latch.cc.o
.PHONY : src/sync/hybrid_latch.o

# target to build an object file
src/sync/hybrid_latch.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/hybrid_latch.cc.o
.PHONY : src/sync/hybrid_latch.cc.o

src/sync/hybrid_latch.i: src/sync/hybrid_latch.cc.i
.PHONY : src/sync/hybrid_latch.i

# target to preprocess a source file
src/sync/hybrid_latch.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/hybrid_latch.cc.i
.PHONY : src/sync/hybrid_latch.cc.i

src/sync/hybrid_latch.s: src/sync/hybrid_latch.cc.s
.PHONY : src/sync/hybrid_latch.s

# target to generate assembly for a file
src/sync/hybrid_latch.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/hybrid_latch.cc.s
.PHONY : src/sync/hybrid_latch.cc.s

src/sync/page_guard/exclusive_guard.o: src/sync/page_guard/exclusive_guard.cc.o
.PHONY : src/sync/page_guard/exclusive_guard.o

# target to build an object file
src/sync/page_guard/exclusive_guard.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/page_guard/exclusive_guard.cc.o
.PHONY : src/sync/page_guard/exclusive_guard.cc.o

src/sync/page_guard/exclusive_guard.i: src/sync/page_guard/exclusive_guard.cc.i
.PHONY : src/sync/page_guard/exclusive_guard.i

# target to preprocess a source file
src/sync/page_guard/exclusive_guard.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/page_guard/exclusive_guard.cc.i
.PHONY : src/sync/page_guard/exclusive_guard.cc.i

src/sync/page_guard/exclusive_guard.s: src/sync/page_guard/exclusive_guard.cc.s
.PHONY : src/sync/page_guard/exclusive_guard.s

# target to generate assembly for a file
src/sync/page_guard/exclusive_guard.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/page_guard/exclusive_guard.cc.s
.PHONY : src/sync/page_guard/exclusive_guard.cc.s

src/sync/page_guard/optimistic_guard.o: src/sync/page_guard/optimistic_guard.cc.o
.PHONY : src/sync/page_guard/optimistic_guard.o

# target to build an object file
src/sync/page_guard/optimistic_guard.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/page_guard/optimistic_guard.cc.o
.PHONY : src/sync/page_guard/optimistic_guard.cc.o

src/sync/page_guard/optimistic_guard.i: src/sync/page_guard/optimistic_guard.cc.i
.PHONY : src/sync/page_guard/optimistic_guard.i

# target to preprocess a source file
src/sync/page_guard/optimistic_guard.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/page_guard/optimistic_guard.cc.i
.PHONY : src/sync/page_guard/optimistic_guard.cc.i

src/sync/page_guard/optimistic_guard.s: src/sync/page_guard/optimistic_guard.cc.s
.PHONY : src/sync/page_guard/optimistic_guard.s

# target to generate assembly for a file
src/sync/page_guard/optimistic_guard.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/page_guard/optimistic_guard.cc.s
.PHONY : src/sync/page_guard/optimistic_guard.cc.s

src/sync/page_guard/page_guard.o: src/sync/page_guard/page_guard.cc.o
.PHONY : src/sync/page_guard/page_guard.o

# target to build an object file
src/sync/page_guard/page_guard.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/page_guard/page_guard.cc.o
.PHONY : src/sync/page_guard/page_guard.cc.o

src/sync/page_guard/page_guard.i: src/sync/page_guard/page_guard.cc.i
.PHONY : src/sync/page_guard/page_guard.i

# target to preprocess a source file
src/sync/page_guard/page_guard.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/page_guard/page_guard.cc.i
.PHONY : src/sync/page_guard/page_guard.cc.i

src/sync/page_guard/page_guard.s: src/sync/page_guard/page_guard.cc.s
.PHONY : src/sync/page_guard/page_guard.s

# target to generate assembly for a file
src/sync/page_guard/page_guard.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/page_guard/page_guard.cc.s
.PHONY : src/sync/page_guard/page_guard.cc.s

src/sync/page_guard/shared_guard.o: src/sync/page_guard/shared_guard.cc.o
.PHONY : src/sync/page_guard/shared_guard.o

# target to build an object file
src/sync/page_guard/shared_guard.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/page_guard/shared_guard.cc.o
.PHONY : src/sync/page_guard/shared_guard.cc.o

src/sync/page_guard/shared_guard.i: src/sync/page_guard/shared_guard.cc.i
.PHONY : src/sync/page_guard/shared_guard.i

# target to preprocess a source file
src/sync/page_guard/shared_guard.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/page_guard/shared_guard.cc.i
.PHONY : src/sync/page_guard/shared_guard.cc.i

src/sync/page_guard/shared_guard.s: src/sync/page_guard/shared_guard.cc.s
.PHONY : src/sync/page_guard/shared_guard.s

# target to generate assembly for a file
src/sync/page_guard/shared_guard.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/page_guard/shared_guard.cc.s
.PHONY : src/sync/page_guard/shared_guard.cc.s

src/sync/page_state.o: src/sync/page_state.cc.o
.PHONY : src/sync/page_state.o

# target to build an object file
src/sync/page_state.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/page_state.cc.o
.PHONY : src/sync/page_state.cc.o

src/sync/page_state.i: src/sync/page_state.cc.i
.PHONY : src/sync/page_state.i

# target to preprocess a source file
src/sync/page_state.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/page_state.cc.i
.PHONY : src/sync/page_state.cc.i

src/sync/page_state.s: src/sync/page_state.cc.s
.PHONY : src/sync/page_state.s

# target to generate assembly for a file
src/sync/page_state.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/sync/page_state.cc.s
.PHONY : src/sync/page_state.cc.s

src/transaction/transaction.o: src/transaction/transaction.cc.o
.PHONY : src/transaction/transaction.o

# target to build an object file
src/transaction/transaction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/transaction/transaction.cc.o
.PHONY : src/transaction/transaction.cc.o

src/transaction/transaction.i: src/transaction/transaction.cc.i
.PHONY : src/transaction/transaction.i

# target to preprocess a source file
src/transaction/transaction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/transaction/transaction.cc.i
.PHONY : src/transaction/transaction.cc.i

src/transaction/transaction.s: src/transaction/transaction.cc.s
.PHONY : src/transaction/transaction.s

# target to generate assembly for a file
src/transaction/transaction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/transaction/transaction.cc.s
.PHONY : src/transaction/transaction.cc.s

src/transaction/transaction_manager.o: src/transaction/transaction_manager.cc.o
.PHONY : src/transaction/transaction_manager.o

# target to build an object file
src/transaction/transaction_manager.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/transaction/transaction_manager.cc.o
.PHONY : src/transaction/transaction_manager.cc.o

src/transaction/transaction_manager.i: src/transaction/transaction_manager.cc.i
.PHONY : src/transaction/transaction_manager.i

# target to preprocess a source file
src/transaction/transaction_manager.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/transaction/transaction_manager.cc.i
.PHONY : src/transaction/transaction_manager.cc.i

src/transaction/transaction_manager.s: src/transaction/transaction_manager.cc.s
.PHONY : src/transaction/transaction_manager.s

# target to generate assembly for a file
src/transaction/transaction_manager.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/leanstore.dir/build.make CMakeFiles/leanstore.dir/src/transaction/transaction_manager.cc.s
.PHONY : src/transaction/transaction_manager.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... LibLz4"
	@echo "... Libyyjson"
	@echo "... check-format"
	@echo "... check-tidy"
	@echo "... check-tidy-full"
	@echo "... format"
	@echo "... Filesystem_Aging"
	@echo "... Filesystem_Gitclone"
	@echo "... Filesystem_Wiki"
	@echo "... Filesystem_YCSB"
	@echo "... LeanStore_Aging"
	@echo "... LeanStore_Email"
	@echo "... LeanStore_FB_WebServer"
	@echo "... LeanStore_Flashbench"
	@echo "... LeanStore_Gitclone"
	@echo "... LeanStore_IndexWiki"
	@echo "... LeanStore_TPCC"
	@echo "... LeanStore_URL"
	@echo "... LeanStore_Wiki"
	@echo "... LeanStore_WikiTitle"
	@echo "... LeanStore_YCSB"
	@echo "... MicroBitmap"
	@echo "... MicroCompression"
	@echo "... MicroFreePages"
	@echo "... MicroQueue"
	@echo "... MicroSHA2"
	@echo "... MicroSearch"
	@echo "... MySQL_YCSB"
	@echo "... Postgres_YCSB"
	@echo "... SQLite_YCSB"
	@echo "... croaring"
	@echo "... fsst"
	@echo "... leanstore"
	@echo "... leanstore_bm"
	@echo "... pqxx"
	@echo "... sha256"
	@echo "... typefold"
	@echo "... src/buffer/buffer_manager.o"
	@echo "... src/buffer/buffer_manager.i"
	@echo "... src/buffer/buffer_manager.s"
	@echo "... src/buffer/resident_set.o"
	@echo "... src/buffer/resident_set.i"
	@echo "... src/buffer/resident_set.s"
	@echo "... src/common/concurrent_queue.o"
	@echo "... src/common/concurrent_queue.i"
	@echo "... src/common/concurrent_queue.s"
	@echo "... src/common/utils.o"
	@echo "... src/common/utils.i"
	@echo "... src/common/utils.s"
	@echo "... src/common/worker_pool.o"
	@echo "... src/common/worker_pool.i"
	@echo "... src/common/worker_pool.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/env.o"
	@echo "... src/env.i"
	@echo "... src/env.s"
	@echo "... src/leanstore.o"
	@echo "... src/leanstore.i"
	@echo "... src/leanstore.s"
	@echo "... src/recovery/group_commit.o"
	@echo "... src/recovery/group_commit.i"
	@echo "... src/recovery/group_commit.s"
	@echo "... src/recovery/log_manager.o"
	@echo "... src/recovery/log_manager.i"
	@echo "... src/recovery/log_manager.s"
	@echo "... src/recovery/log_worker.o"
	@echo "... src/recovery/log_worker.i"
	@echo "... src/recovery/log_worker.s"
	@echo "... src/statistics.o"
	@echo "... src/statistics.i"
	@echo "... src/statistics.s"
	@echo "... src/storage/blob/blob_manager.o"
	@echo "... src/storage/blob/blob_manager.i"
	@echo "... src/storage/blob/blob_manager.s"
	@echo "... src/storage/blob/compressor.o"
	@echo "... src/storage/blob/compressor.i"
	@echo "... src/storage/blob/compressor.s"
	@echo "... src/storage/btree/locking.o"
	@echo "... src/storage/btree/locking.i"
	@echo "... src/storage/btree/locking.s"
	@echo "... src/storage/btree/node.o"
	@echo "... src/storage/btree/node.i"
	@echo "... src/storage/btree/node.s"
	@echo "... src/storage/btree/tree.o"
	@echo "... src/storage/btree/tree.i"
	@echo "... src/storage/btree/tree.s"
	@echo "... src/storage/extent/extent_list.o"
	@echo "... src/storage/extent/extent_list.i"
	@echo "... src/storage/extent/extent_list.s"
	@echo "... src/storage/free_page_manager.o"
	@echo "... src/storage/free_page_manager.i"
	@echo "... src/storage/free_page_manager.s"
	@echo "... src/storage/space/backend/aio.o"
	@echo "... src/storage/space/backend/aio.i"
	@echo "... src/storage/space/backend/aio.s"
	@echo "... src/storage/space/backend/io_backend.o"
	@echo "... src/storage/space/backend/io_backend.i"
	@echo "... src/storage/space/backend/io_backend.s"
	@echo "... src/storage/space/backend/zns.o"
	@echo "... src/storage/space/backend/zns.i"
	@echo "... src/storage/space/backend/zns.s"
	@echo "... src/storage/space/device.o"
	@echo "... src/storage/space/device.i"
	@echo "... src/storage/space/device.s"
	@echo "... src/storage/space/doublewrite.o"
	@echo "... src/storage/space/doublewrite.i"
	@echo "... src/storage/space/doublewrite.s"
	@echo "... src/storage/space/garbage_collector.o"
	@echo "... src/storage/space/garbage_collector.i"
	@echo "... src/storage/space/garbage_collector.s"
	@echo "... src/storage/space/io_interface.o"
	@echo "... src/storage/space/io_interface.i"
	@echo "... src/storage/space/io_interface.s"
	@echo "... src/storage/space/space_manager.o"
	@echo "... src/storage/space/space_manager.i"
	@echo "... src/storage/space/space_manager.s"
	@echo "... src/sync/hybrid_guard.o"
	@echo "... src/sync/hybrid_guard.i"
	@echo "... src/sync/hybrid_guard.s"
	@echo "... src/sync/hybrid_latch.o"
	@echo "... src/sync/hybrid_latch.i"
	@echo "... src/sync/hybrid_latch.s"
	@echo "... src/sync/page_guard/exclusive_guard.o"
	@echo "... src/sync/page_guard/exclusive_guard.i"
	@echo "... src/sync/page_guard/exclusive_guard.s"
	@echo "... src/sync/page_guard/optimistic_guard.o"
	@echo "... src/sync/page_guard/optimistic_guard.i"
	@echo "... src/sync/page_guard/optimistic_guard.s"
	@echo "... src/sync/page_guard/page_guard.o"
	@echo "... src/sync/page_guard/page_guard.i"
	@echo "... src/sync/page_guard/page_guard.s"
	@echo "... src/sync/page_guard/shared_guard.o"
	@echo "... src/sync/page_guard/shared_guard.i"
	@echo "... src/sync/page_guard/shared_guard.s"
	@echo "... src/sync/page_state.o"
	@echo "... src/sync/page_state.i"
	@echo "... src/sync/page_state.s"
	@echo "... src/transaction/transaction.o"
	@echo "... src/transaction/transaction.i"
	@echo "... src/transaction/transaction.s"
	@echo "... src/transaction/transaction_manager.o"
	@echo "... src/transaction/transaction_manager.i"
	@echo "... src/transaction/transaction_manager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

